title NovaArch Live (x86_64, gaming daily - zen)
linux /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux-zen
initrd /%INSTALL_DIR%/boot/x86_64/initramfs-linux-zen.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% systemd.gpt_auto=no
