---
modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - netinstall
    - partition
    - users
    - summary
  - exec:
    - netinstall
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - shellprocess
    - bootloader
    - umount

branding: novaarch
prompt-install: true
dont-chroot: false
oem-setup: false
