monitor=,preferred,auto,1

env = XCURSOR_SIZE,24
env = WLR_NO_HARDWARE_CURSORS,1

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
    sensitivity = 0
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(d63f3fee)
    col.inactive_border = rgba(3b4252aa)
    layout = dwindle
}

decoration {
    rounding = 8
    blur {
        enabled = true
        size = 5
        passes = 2
    }
}

animations {
    enabled = true
}

exec-once = waybar
exec-once = nm-applet --indicator
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = swaybg -i /usr/share/backgrounds/novaarch/wallpaper-1.svg -m fill
exec-once = /usr/local/bin/novaarch-web-wallpaper --last
exec-once = /usr/local/bin/novaarch-welcome-autostart

$mainMod = SUPER

bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, Q, killactive,
bind = $mainMod, E, exec, thunar
bind = $mainMod, R, exec, /usr/local/bin/novaarch-start-menu
bind = $mainMod SHIFT, W, exec, /usr/local/bin/novaarch-wallpaper-selector
bind = $mainMod SHIFT, C, exec, /usr/local/bin/novaarch-control-center
bind = $mainMod SHIFT, A, exec, /usr/local/bin/novaarch-welcome
bind = $mainMod, L, exec, swaylock -f -c 111318
bind = $mainMod, F, fullscreen
bind = $mainMod SHIFT, E, exit

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
